shop_api_product_show_details_by_slug:
    path: /products-by-slug/{slug}
    methods: [GET]
    defaults:
        _controller: sylius.shop_api_plugin.controller.product.show_product_details_by_slug_action

shop_api_add_product_review_by_slug:
    path: /products-by-slug/{slug}/reviews
    methods: [POST]
    defaults:
        _controller: sylius.shop_api_plugin.controller.product.add_review_action

shop_api_product_show_catalog_by_slug:
    path: /taxon-products-by-slug/{taxonomySlug}
    methods: [GET]
    defaults:
        _controller: sylius.shop_api_plugin.controller.product.show_product_catalog_by_slug_action
    requirements:
        taxonomySlug: .+

shop_api_product_show_reviews_by_slug:
    path: /products-by-slug/{slug}/reviews
    methods: [GET]
    defaults:
        _controller: sylius.shop_api_plugin.controller.product.show_product_reviews_by_slug_action
