sylius_shop_api_product_show_details_by_code:
    path: /products/{code}
    methods: [GET]
    defaults:
        _controller: sylius.shop_api_plugin.controller.product.show_product_details_by_code_action

sylius_shop_api_product_show_catalog_by_code:
    path: /taxon-products/{code}
    methods: [GET]
    defaults:
        _controller: sylius.shop_api_plugin.controller.product.show_product_catalog_by_taxon_code_action

sylius_shop_api_product_show_reviews_by_code:
    path: /products/{code}/reviews
    methods: [GET]
    defaults:
        _controller: sylius.shop_api_plugin.controller.product.show_product_reviews_by_code_action

sylius_shop_api_add_product_review_by_code:
    path: /products/{code}/reviews
    methods: [POST]
    defaults:
        _controller: sylius.shop_api_plugin.controller.product.add_review_by_code_action
