jms_serializer:
    metadata:
        directories:
            sylius-shop-api-taxon:
                namespace_prefix: "Sylius\\ShopApiPlugin\\View\\Taxon"
                path: "@SyliusShopApiPlugin/Resources/config/serializer/Taxon"
            sylius-shop-api-product:
                namespace_prefix: "Sylius\\ShopApiPlugin\\View\\Product"
                path: "@SyliusShopApiPlugin/Resources/config/serializer/Product"
            sylius-shop-api-placed-order:
                namespace_prefix: "Sylius\\ShopApiPlugin\\View\\Order"
                path : "@SyliusShopApiPlugin/Resources/config/serializer/Order"

framework:
    messenger:
        buses:
            sylius_shop_api_plugin.command_bus:
                middleware:
                    - doctrine_transaction

sylius_customer:
    resources:
        customer:
            classes:
                controller: Sylius\ShopApiPlugin\Controller\Customer\CustomerController
