Sylius\ShopApiPlugin\View\ImageView:
    exclusion_policy: ALL
    xml_root_name: image_view
    properties:
        code:
            expose: true
            type: string
        path:
            expose: true
            type: string
        cachedPath:
            expose: true
            type: string
