Sylius\ShopApiPlugin\View\ProductView:
    exclusion_policy: ALL
    xml_root_name: product_view
    properties:
        code:
            expose: true
            type: string
        name:
            expose: true
            type: string
        slug:
            expose: true
            type: string
        breadcrumb:
            expose: true
            type: string
        description:
            expose: true
            type: string
        shortDescription:
            expose: true
            type: string
        metaKeywords:
            expose: true
            type: string
        metaDescription:
            expose: true
            type: string
        averageRating:
            expose: true
            type: integer
        taxons:
            expose: true
        variants:
            expose: true
            type: array
        images:
            expose: true
            type: array
        attributes:
            expose: true
            type: array
        associations:
            expose: true
            type: array
    relations:
        -   rel: self
            href:
                route: shop_api_product_show_details_by_slug
                parameters:
                    slug: expr(object.slug)
